<?php

/**
 * @file
 * Primary module hooks for IZI Entity module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function izi_entity_theme() {
  return [
    'izi_object' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for izi object templates.
 *
 * Default template: izi-object.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the izi object information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_izi_object(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function izi_entity_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish izi objects.
      $storage = \Drupal::entityTypeManager()->getStorage('izi_object');
      $izi_object_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($izi_object_ids) as $izi_object) {
        $izi_object->set('status', FALSE);
        $izi_object->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize izi objects.
      $storage = \Drupal::entityTypeManager()->getStorage('izi_object');
      $izi_object_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($izi_object_ids) as $izi_object) {
        $izi_object->setOwnerId(0);
        $izi_object->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function izi_entity_user_predelete(UserInterface $account) {
  // Delete izi objects.
  $storage = \Drupal::entityTypeManager()->getStorage('izi_object');
  $izi_object_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $izi_objects = $storage->loadMultiple($izi_object_ids);
  $storage->delete($izi_objects);
}
