# Schema for the configuration files of the Izi cognito module.
izi_cognito.settings:
  type: config_object
  label: 'Signup Terms & Conditions'
  mapping:
    signup_terms_confirm:
      type: text
      label: 'By registering & authenticating into this site you automatically agree to the terms & conditions.'

